kadi/modules/main/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kadi/modules/main/api/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from . import internal
from . import v1_0

kadi/modules/main/api/internal/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from . import get

kadi/modules/main/api/v1_0/__init__.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from . import get

kadi/modules/main/blueprint.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from flask import Blueprint
from flask import current_app
from flask import render_template
from flask import request
from flask_limiter.errors import RateLimitExceeded
from flask_login import current_user
from flask_wtf.csrf import CSRFError
from werkzeug.exceptions import HTTPException

import kadi.lib.constants as const
from kadi.ext.talisman import talisman
from kadi.lib.api.core import json_error_response
from kadi.lib.api.utils import is_api_request
from kadi.lib.web import get_error_message
from kadi.lib.web import get_locale


bp = Blueprint("main", __name__, template_folder="templates")


@bp.app_errorhandler(HTTPException)
def _app_errorhandler(e):
    # Before returning any error information, we redirect anonymous users using
    # Flask-Login's functionality to get consistent behaviour with actual unauthorized
    # requests. We ignore CSRF-related errors (as this can interfere with the session
    # user loader) as well as rate limit and server errors.
    if (
        not isinstance(e, (CSRFError, RateLimitExceeded))
        and not e.code >= 500
        and not current_user.is_authenticated
    ):
        return current_app.login_manager.unauthorized()

    # If another pre-request handler aborts with an exception, the nonce will never get
    # created, so we call all Flask-Talisman handlers manually again just in case.
    talisman._force_https()
    talisman._make_nonce()

    if isinstance(e, CSRFError):
        description = (
            f"{e.description} Please try to restart your browser or delete the cookies"
            " for this website and try again."
        )
    elif isinstance(e, RateLimitExceeded):
        description = f"Rate limit exceeded ({e.description}). Please try again later."
    else:
        description = e.description

    if is_api_request():
        response = json_error_response(
            e.code, message=get_error_message(e.code), description=description
        )
    else:
        template = render_template(
            "main/error.html",
            title=e.code,
            status_code=e.code,
            message=get_error_message(e.code),
            description=description,
        )

        response = current_app.response_class(response=template, status=e.code)

    talisman._set_response_headers(response)
    return response


@bp.after_app_request
def _after_app_request(response):
    locale = get_locale()

    locale_cookie_name = current_app.config["LOCALE_COOKIE_NAME"]
    locale_cookie = request.cookies.get(locale_cookie_name)

    if (
        locale != locale_cookie
        and not is_api_request()
        and request.endpoint != "static"
    ):
        response.set_cookie(
            locale_cookie_name,
            value=locale,
            max_age=365 * const.ONE_DAY,
            samesite="Lax",
            secure=current_app.config["LOCALE_COOKIE_SECURE"],
        )

    return response


from . import views  # pylint: disable=unused-import

kadi/modules/main/views.py
# Copyright 2020 Karlsruhe Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from flask import current_app
from flask import render_template
from flask import request
from flask_babel import gettext as _
from flask_login import current_user

from .blueprint import bp
from kadi.modules.collections.models import Collection
from kadi.modules.collections.schemas import CollectionSchema
from kadi.modules.permissions.core import get_permitted_objects
from kadi.modules.records.models import Record
from kadi.modules.records.schemas import RecordSchema
from kadi.version import __version__


@bp.get("/")
def index():
    """The index/home page.

    Will change depending on whether the current user is authenticated or not.
    """
    locales = list(current_app.config["LOCALES"].keys())
    preferred_locale = request.accept_languages.best_match(locales)

    if not current_user.is_authenticated:
        return render_template(
            "main/index.html", version=__version__, preferred_locale=preferred_locale
        )

    records = (
        get_permitted_objects(current_user, "read", "record")
        .filter(Record.state == "active")
        .order_by(Record.last_modified.desc())
        .limit(6)
    )
    collections = (
        get_permitted_objects(current_user, "read", "collection")
        .filter(Collection.state == "active")
        .order_by(Collection.last_modified.desc())
        .limit(6)
    )

    return render_template(
        "main/home.html",
        title=_("Home"),
        preferred_locale=preferred_locale,
        js_resources={
            "records": RecordSchema(many=True, _internal=True).dump(records),
            "collections": CollectionSchema(many=True, _internal=True).dump(
                collections
            ),
        },
    )


@bp.get("/about")
def about():
    """The about page."""
    return render_template("main/about.html", title=_("About"), version=__version__)


@bp.get("/help")
def help():
    """The help page."""
    return render_template("main/help.html", title=_("Help"))

kadi/modules/main/templates/main/about.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block breadcrumbs %}
  {% snippet "breadcrumb_home" %}
  {% snippet "breadcrumb", url=url_for("main.about"), title=_("About") %}
{% endblock %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-end">
        <a href="{% trans %}https://www.kit.edu/english{% endtrans %}" class="mr-5">
          <img class="img-fluid mb-4" src="{{ static_url('images/kit.png') }}" width="140">
        </a>
        <a href="{% trans %}https://www.iam.kit.edu/cms/english{% endtrans %}">
          <img class="img-fluid mb-4" src="{{ static_url('images/iam.png') }}" width="120">
        </a>
      </div>
      <p>
        <strong>Kadi4Mat</strong> is the <strong>Karlsruhe Data Infrastructure for Materials Science</strong>, an open
        source software for managing research data.
        It is being developed as part of several research projects at the
        <a href="{% trans %}https://www.iam.kit.edu/cms/english{% endtrans %}">
          <strong>Institute for Applied Materials - Computational Materials Science (IAM-CMS)</strong>
        </a>
        of the
        <a href="{% trans %}https://www.kit.edu/english{% endtrans %}">
          <strong>Karlsruhe Institute of Technology (KIT).</strong>
        </a>
      </p>
      <p>
        The goal of this project is to combine the ability to manage and exchange data, the <em>repository</em>, with
        the possibility to analyze, visualize and transform said data, the <em>electronic lab notebook (ELN)</em>.
        Kadi4Mat is supposed to support a close cooperation between experimenters, theorists and simulators, especially
        in materials science, and enable the acquisition of new knowledge and the development of novel materials. This
        is made possible by employing a modular and generic architecture, which allows to cover the specific needs of
        different scientists, each utilizing unique workflows. At the same time, this opens up the possibility to easily
        branch out into other disciplines in the future.
      </p>
      <hr>
      <h5 class="font-weight-bold">Further links</h5>
      <ul class="mb-0 pl-4">
        <li>
          More information:
          <a href="https://kadi.iam-cms.kit.edu">
            <strong>https://kadi.iam-cms.kit.edu</strong>
          </a>
        </li>
        <li>
          Source code:
          <a href="https://gitlab.com/iam-cms/kadi">
            <strong>https://gitlab.com/iam-cms/kadi</strong>
          </a>
        </li>
        <li>
          Documentation:
          <ul class="mb-0 pl-4">
            <li>
              Stable (reflecting the latest release):
              <a href="https://kadi4mat.readthedocs.io/en/stable">
                <strong>https://kadi4mat.readthedocs.io/en/stable</strong>
              </a>
            </li>
            <li>
              Latest (reflecting the <em>master</em> branch):
              <a href="https://kadi4mat.readthedocs.io/en/latest">
                <strong>https://kadi4mat.readthedocs.io/en/latest</strong>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    {% if current_user.is_authenticated %}
      <div class="card-footer">
        <a href="https://kadi4mat.readthedocs.io/en/stable/HISTORY.html" class="badge badge-primary font-weight-normal">
          Kadi4Mat v{{ version }}
        </a>
      </div>
    {% endif %}
  </div>
{% endblock %}

kadi/modules/main/templates/main/error.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content_wrapper %}
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <h1 class="text-center">{{ status_code }}</h1>
      <h5 class="text-center">{{ message }}</h5>
      <p class="text-center">{{ description }}</p>
      <p class="text-center">
        <a href="{{ url_for('main.index') }}">
          <strong>{% trans %}Return to the homepage.{% endtrans %}</strong>
        </a>
      </p>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/help.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block breadcrumbs %}
  {% snippet "breadcrumb_home" %}
  {% snippet "breadcrumb", url=url_for("main.help"), title=_("Help") %}
{% endblock %}

{% block content %}
  <div class="card">
    <div class="row">
      <div class="d-none d-lg-block col-lg-4 col-xl-3">
        <nav id="help-navbar" class="navbar flex-column bg-light overflow-auto vh-75">
          <nav class="nav nav-pills flex-column">
            <a class="nav-link my-1" href="#login">
              <strong>Logging in</strong>
            </a>
            <a class="nav-link my-1" href="#navigation">
              <strong>Navigation</strong>
            </a>
            <a class="nav-link my-1" href="#records">
              <strong>Records</strong>
            </a>
            <nav class="nav nav-pills flex-column">
              <a class="nav-link ml-3 my-1" href="#new-record">Creating a new record</a>
              <a class="nav-link ml-3 my-1" href="#search-record">Searching existing records</a>
              <a class="nav-link ml-3 my-1" href="#manage-record">Managing existing records</a>
            </nav>
            <a class="nav-link my-1" href="#collections">
              <strong>Collections</strong>
            </a>
            <nav class="nav nav-pills flex-column">
              <a class="nav-link ml-3 my-1" href="#new-collection">Creating a new collection</a>
              <a class="nav-link ml-3 my-1" href="#manage-collection">Managing existing collections</a>
            </nav>
            <a class="nav-link my-1" href="#groups">
              <strong>Groups</strong>
            </a>
            <nav class="nav nav-pills flex-column">
              <a class="nav-link ml-3 my-1" href="#new-group">Creating a new group</a>
              <a class="nav-link ml-3 my-1" href="#manage-group">Managing existing groups</a>
            </nav>
            <a class="nav-link my-1" href="#templates">
              <strong>Templates</strong>
            </a>
            <nav class="nav nav-pills flex-column">
              <a class="nav-link ml-3 my-1" href="#new-template">Creating a new template</a>
              <a class="nav-link ml-3 my-1" href="#manage-template">Managing existing templates</a>
            </nav>
            <a class="nav-link my-1" href="#users">
              <strong>Users</strong>
            </a>
            <a class="nav-link my-1" href="#settings">
              <strong>Settings</strong>
            </a>
          </nav>
        </nav>
      </div>
      <div class="col-12 col-lg-8 col-xl-9">
        <div class="overflow-auto vh-75" data-spy="scroll" data-target="#help-navbar" data-offset="20">
          <div class="mx-3 mt-3 ml-lg-0">
            {% include "main/snippets/help/login.html" %}
            <hr>
            {% include "main/snippets/help/navigation.html" %}
            <hr>
            {% include "main/snippets/help/records.html" %}
            <hr>
            {% include "main/snippets/help/collections.html" %}
            <hr>
            {% include "main/snippets/help/groups.html" %}
            <hr>
            {% include "main/snippets/help/templates.html" %}
            <hr>
            {% include "main/snippets/help/users.html" %}
            <hr>
            {% include "main/snippets/help/settings.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/home.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block content %}
  <language-prompt preferred-locale="{{ preferred_locale }}"></language-prompt>

  {% include "main/snippets/header.html" %}

  <div class="card my-4">
    <div class="card-body">
      <div class="row align-items-center">
        <div class="col-lg-7 mb-4 mb-lg-0">
          <h5>
            <strong>{% trans %}Welcome to Kadi4Mat.{% endtrans %}</strong>
          </h5>
          {% trans %}You are currently logged in as{% endtrans %}
          <identity-popover :user="{{ json_user(current_user) }}"></identity-popover>.
        </div>
        <div class="col-lg-5">
          <a href="{{ url_for('main.about') }}" class="btn btn-sm btn-block btn-light">
            {% trans %}About Kadi4Mat{% endtrans %}
          </a>
          <a href="{{ url_for('main.help') }}" class="btn btn-sm btn-block btn-light">
            <i class="fas fa-question-circle"></i> {% trans %}Help{% endtrans %}
          </a>
        </div>
      </div>
    </div>
  </div>
  <h4>
    <strong>{% trans %}Get started{% endtrans %}</strong>
  </h4>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row d-flex align-items-center">
        <div class="col-xl-4 mb-4 mb-xl-0">
          {% if has_permission(current_user, "create", "record", None) %}
            <a class="btn btn-sm btn-primary btn-block" href="{{ url_for('records.new_record') }}">
              <i class="fas fa-plus-square"></i> {% trans %}Create new record{% endtrans %}
            </a>
          {% endif %}
          <a class="btn btn-sm btn-light btn-block" href="{{ url_for('records.records') }}">
            <i class="fas fa-search"></i> {% trans %}Search existing records{% endtrans %}
          </a>
        </div>
        <div class="col-xl-8">
          {% trans trimmed %}
            Records are the basic components of Kadi4Mat, as they contain data and connect it with metadata.
          {% endtrans %}
          {% trans trimmed %}
            The data of a record can either consist of a single file or of multiple files (e.g. a series of multiple
            images) all sharing the same metadata.
          {% endtrans %}
        </div>
      </div>
    </div>
  </div>
  <div v-if="kadi.js_resources.records.length > 0 || kadi.js_resources.collections.length > 0">
    <h4 class="mb-3">
      <strong>{% trans %}Latest updates{% endtrans %}</strong>
    </h4>
    <div v-if="kadi.js_resources.records.length > 0">
      <div class="d-flex justify-content-between">
        <h5>
          <strong>{% trans %}Records{% endtrans %}</strong>
        </h5>
        <a href="{{ url_for('records.records') }}">
          <strong>{% trans %}View all{% endtrans %}</strong>
        </a>
      </div>
      <resource-index-view :resources="kadi.js_resources.records"></resource-index-view>
      <br v-if="kadi.js_resources.collections.length > 0">
    </div>
    <div v-if="kadi.js_resources.collections.length > 0">
      <div class="d-flex justify-content-between">
        <h5>
          <strong>{% trans %}Collections{% endtrans %}</strong>
        </h5>
        <a href="{{ url_for('collections.collections') }}">
          <strong>{% trans %}View all{% endtrans %}</strong>
        </a>
      </div>
      <resource-index-view :resources="kadi.js_resources.collections"></resource-index-view>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/index.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

{% extends "base.html" %}

{% block meta %}
  <link rel="preload" href="{{ static_url('images/kadi_bg.png') }}" as="image" type="image/png">
  {# Do not use the manifest mapping because the regular font file is referenced in the style sheet. #}
  <link rel="preload"
        href="{{ url_for('static', filename='dist/fonts/lato-normal.woff2') }}"
        as="font"
        type="font/woff2"
        crossorigin>
  <link rel="preload"
        href="{{ url_for('static', filename='dist/fonts/lato-bold.woff2') }}"
        as="font"
        type="font/woff2"
        crossorigin>
  <link rel="preload"
        href="{{ url_for('static', filename='dist/fonts/fa-solid-900.woff2') }}"
        as="font"
        type="font/woff2"
        crossorigin>
{% endblock %}

{% block content %}
  <language-prompt preferred-locale="{{ preferred_locale }}"></language-prompt>

  {% include "main/snippets/header.html" %}

  <div class="card mt-4">
    <div class="card-body">
      <div class="row align-items-center">
        <div class="col-lg-7 mb-4 mb-lg-0">
          <h5>
            <strong>{% trans %}Welcome to Kadi4Mat.{% endtrans %}</strong>
          </h5>
          {% trans trimmed %}
            Kadi4Mat is the <strong>Karlsruhe Data Infrastructure for Materials Science</strong>, an open source
            software for managing research data.
          {% endtrans %}
        </div>
        <div class="col-lg-5">
          <a href="{{ url_for('main.about') }}" class="btn btn-sm btn-block btn-light">
            {% trans %}About Kadi4Mat{% endtrans %}
          </a>
          <a href="{{ url_for('main.help') }}" class="btn btn-sm btn-block btn-light">
            <i class="fas fa-question-circle"></i> {% trans %}Help{% endtrans %}
          </a>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="row">
        <div class="col-lg-5 offset-lg-7">
          <a href="{{ url_for('accounts.login') }}" class="btn btn-block btn-primary">
            <i class="fas fa-sign-in-alt"></i> {% trans %}Login{% endtrans %}
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

kadi/modules/main/templates/main/snippets/header.html
{# Copyright 2021 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

<div class="card bg-primary text-white">
  <div class="row align-items-center">
    <div class="col-lg-7 d-none d-lg-block">
      <img class="img-fluid" width="500" src="{{ static_url('images/kadi_bg.png') }}">
    </div>
    <div class="col-lg-5 m-3 m-lg-0 text-center">
      <h5>
        <strong>{% trans %}Karlsruhe Data Infrastructure{% endtrans %}</strong>
      </h5>
      {% trans %}for Materials Science{% endtrans %}
    </div>
  </div>
</div>

kadi/modules/main/templates/main/snippets/help/collections.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

<h4 id="collections">Collections</h4>
<p>
  Collections represent simple, logical groupings of multiple records.
</p>
<h5 id="new-collection">Creating a new collection</h5>
<p>
  Creating a new collection is very similar to <a href="#new-record"><strong>creating a new record</strong></a>, except
  that only some basic metadata is necessary. Similarly, no files can be uploaded. Instead, the application will
  redirect to the overview of the collection right away.
</p>
<h5 id="manage-collection">Managing existing collections</h5>
<p>
  Similar to records, collections have their own navigation menu, offering different views for linking resources,
  managing access permissions, editing metadata and viewing revisions. As the menu items are very similar to those of
  records, please refer to <a href="#manage-record"><strong>managing existing records</strong></a> for more information.
</p>

kadi/modules/main/templates/main/snippets/help/settings.html
{# Copyright 2020 Karlsruhe Institute of Technology
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License. #}

<h4 id="settings">Settings</h4>
<p>
  The settings allow managing everything not directly related to the actual creation and management of resources.
  Similar to managing resources, there are multiple menu items to navigate to different views:
</p>
<dl class="row">
  <dt class="col-md-2">Profile</dt>
  <dd class="col-md-10">
    In this view it is possible to change basic user information, which is displayed on a user's profile. Note that some
    options might be disabled, depending on the type of the user account.
  </dd>
  <dt class="col-md-2">Password</dt>
  <dd class="col-md-10">
    In this menu, users can change their password. Depending on the type of user account this menu item may be hidden.
  </dd>
  <dt class="col-md-2">Access tokens</dt>
  <dd class="col-md-10">
    Creating a personal access token (PAT) gives access to the HTTP API that Kadi4Mat provides. This API makes it
    possible to programmatically interact with most of the resources that can be managed via the graphical user
    interface of Kadi4Mat by sending suitable HTTP requests to the different endpoints the API provides. Detailed
    information about the API can be found in Kadi4Mat's
    <a href="{{ url_for('main.about') }}"><strong>documentation</strong></a>.
  </dd>
  <dt class="col-md-2">Connected services</dt>
  <dd class="col-md-10">
    In this menu, users can manage their connections with different third party services. Each service has to be
    registered as a plugin in the application and can be used for different tasks, e.g. publishing records.
  </dd>
  <dt class="col-md-2">Trash</dt>
  <dd class="col-md-10">
    This is where deleted resources can be found, namely deleted records, collections or groups. Resources can either be
    restored or deleted completely. The latter will happen automatically after
    {{ config["RESOURCES_MAX_AGE"] | duration }}. Note that only the creator of a resource can restore or completely
    delete them.
  </dd>
</dl>